// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset(
  'package:libmuslim_dart/libmuslim_dart_bindings_generated.dart',
)
library;

import 'dart:ffi' as ffi;

/// Format a decimal-hours time (e.g. 5.5) into "HH:MM" in outBuffer.
/// Minutes are rounded up (Kemenag convention).
///
/// A value outside [0, 24) is reduced onto the clock face first, so 25.075
/// renders as "01:05" and -0.104 as "23:54". The result names an hour of the
/// day and cannot say which day, so read the raw double if you need that.
///
/// A non-finite value renders as "--:--". Six bytes are enough for either.
@ffi.Native<ffi.Void Function(ffi.Double, ffi.Pointer<ffi.Char>, ffi.Size)>()
external void format_time_hm(
  double timeHours,
  ffi.Pointer<ffi.Char> outBuffer,
  int bufSize,
);

/// Format a decimal-hours time (e.g. 5.5) into "HH:MM:SS" in outBuffer.
/// Seconds are rounded to nearest; use format_time_hm for the Kemenag
/// round-up-to-the-minute convention.
///
/// The same reduction applies, so -0.104 renders as "23:53:46". A non-finite
/// value renders as "--:--:--". Nine bytes are enough for either.
@ffi.Native<ffi.Void Function(ffi.Double, ffi.Pointer<ffi.Char>, ffi.Size)>()
external void format_time_hms(
  double timeHours,
  ffi.Pointer<ffi.Char> outBuffer,
  int bufSize,
);

/// Look up the parameter set for a calculation method.
/// Returns: pointer to a static MethodParams, or NULL if method is out of range.
@ffi.Native<ffi.Pointer<MethodParams> Function(ffi.UnsignedInt)>(
  symbol: 'method_params_get',
)
external ffi.Pointer<MethodParams> _method_params_get(int method);

ffi.Pointer<MethodParams> method_params_get(CalcMethod method) =>
    _method_params_get(method.value);

/// Map a method key string (e.g. "kemenag") to its CalcMethod.
/// Returns: the matching method, or CALC_CUSTOM if name is NULL or unknown.
@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<ffi.Char>)>(
  symbol: 'method_from_string',
)
external int _method_from_string(ffi.Pointer<ffi.Char> name);

CalcMethod method_from_string(ffi.Pointer<ffi.Char> name) =>
    CalcMethod.fromValue(_method_from_string(name));

/// Map a CalcMethod back to its key string (e.g. "kemenag").
/// Returns: the key, or "custom" if the method has no key.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.UnsignedInt)>(
  symbol: 'method_to_string',
)
external ffi.Pointer<ffi.Char> _method_to_string(int method);

ffi.Pointer<ffi.Char> method_to_string(CalcMethod method) =>
    _method_to_string(method.value);

/// Compute all prayer times for a date and location using the given method.
/// Returns times as decimal hours in local time; high-latitude fallbacks apply.
@ffi.Native<
  PrayerTimes Function(
    ffi.Int,
    ffi.Int,
    ffi.Int,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Pointer<MethodParams>,
  )
>()
external PrayerTimes calculate_prayer_times(
  int year,
  int month,
  int day,
  double latitude,
  double longitude,
  double timezone,
  ffi.Pointer<MethodParams> params,
);

/// ── Calculation-method catalogue ──────────────────────────────────────
enum CalcMethod {
  CALC_MWL(0),
  CALC_MAKKAH(1),
  CALC_ISNA(2),
  CALC_EGYPT(3),
  CALC_KARACHI(4),
  CALC_TURKEY(5),
  CALC_SINGAPORE(6),
  CALC_JAKIM(7),
  CALC_KEMENAG(8),
  CALC_FRANCE(9),
  CALC_RUSSIA(10),
  CALC_DUBAI(11),
  CALC_QATAR(12),
  CALC_KUWAIT(13),
  CALC_JORDAN(14),
  CALC_GULF(15),
  CALC_TUNISIA(16),
  CALC_ALGERIA(17),
  CALC_MOROCCO(18),
  CALC_PORTUGAL(19),
  CALC_MOONSIGHTING(20),
  CALC_CUSTOM(21),
  CALC_COUNT(22);

  final int value;
  const CalcMethod(this.value);

  static CalcMethod fromValue(int value) => switch (value) {
    0 => CALC_MWL,
    1 => CALC_MAKKAH,
    2 => CALC_ISNA,
    3 => CALC_EGYPT,
    4 => CALC_KARACHI,
    5 => CALC_TURKEY,
    6 => CALC_SINGAPORE,
    7 => CALC_JAKIM,
    8 => CALC_KEMENAG,
    9 => CALC_FRANCE,
    10 => CALC_RUSSIA,
    11 => CALC_DUBAI,
    12 => CALC_QATAR,
    13 => CALC_KUWAIT,
    14 => CALC_JORDAN,
    15 => CALC_GULF,
    16 => CALC_TUNISIA,
    17 => CALC_ALGERIA,
    18 => CALC_MOROCCO,
    19 => CALC_PORTUGAL,
    20 => CALC_MOONSIGHTING,
    21 => CALC_CUSTOM,
    22 => CALC_COUNT,
    _ => throw ArgumentError('Unknown value for CalcMethod: $value'),
  };
}

enum AsrSchool {
  ASR_STANDARD(1),
  ASR_HANAFI(2);

  final int value;
  const AsrSchool(this.value);

  static AsrSchool fromValue(int value) => switch (value) {
    1 => ASR_STANDARD,
    2 => ASR_HANAFI,
    _ => throw ArgumentError('Unknown value for AsrSchool: $value'),
  };
}

/// What to do for fajr and isha when the Sun never reaches the required
/// depression angle, which happens every summer above roughly 48 degrees.
///
/// This is a property of the calculation authority, not of the library. Most
/// authorities serve jurisdictions where the case never arises and publish no
/// rule at all, so most entries in the method table are HIGHLAT_ANGLE_BASED,
/// which is a computational convention rather than anyone's ruling. See
/// docs/research/2026-08-18-high-latitude-conventions.md.
///
/// Every value except HIGHLAT_NEAREST_LATITUDE is defined in terms of the
/// interval between sunset and sunrise, so none of them can answer inside the
/// polar circle where that interval does not exist. MethodParams.high_lat_ref
/// covers that case separately.
enum HighLatMethod {
  /// no substitution, the time is NaN
  HIGHLAT_NONE(0),

  /// half the night before sunrise, after sunset
  HIGHLAT_MIDDLE_OF_NIGHT(1),

  /// one seventh of the night
  HIGHLAT_ONE_SEVENTH(2),

  /// angle/60 of the night, praytimes.org
  HIGHLAT_ANGLE_BASED(3),

  /// same fraction of the night as at high_lat_ref
  HIGHLAT_NEAREST_LATITUDE(4);

  final int value;
  const HighLatMethod(this.value);

  static HighLatMethod fromValue(int value) => switch (value) {
    0 => HIGHLAT_NONE,
    1 => HIGHLAT_MIDDLE_OF_NIGHT,
    2 => HIGHLAT_ONE_SEVENTH,
    3 => HIGHLAT_ANGLE_BASED,
    4 => HIGHLAT_NEAREST_LATITUDE,
    _ => throw ArgumentError('Unknown value for HighLatMethod: $value'),
  };
}

enum MidnightMode {
  MIDNIGHT_STANDARD(0);

  final int value;
  const MidnightMode(this.value);

  static MidnightMode fromValue(int value) => switch (value) {
    0 => MIDNIGHT_STANDARD,
    _ => throw ArgumentError('Unknown value for MidnightMode: $value'),
  };
}

final class MethodParams extends ffi.Struct {
  external ffi.Pointer<ffi.Char> name;

  @ffi.Double()
  external double fajr_angle;

  /// 0 when isha uses interval instead
  @ffi.Double()
  external double isha_angle;

  /// minutes after maghrib (0 = use angle)
  @ffi.Int()
  external int isha_interval;

  /// minutes after sunset (0 = at sunset)
  @ffi.Int()
  external int maghrib_interval;

  /// shadow factor: 1 = standard, 2 = Hanafi
  @ffi.Int()
  external int asr_shadow;

  @ffi.UnsignedInt()
  external int midnight_modeAsInt;

  MidnightMode get midnight_mode => MidnightMode.fromValue(midnight_modeAsInt);

  /// precautionary minutes added to each time
  @ffi.Int()
  external int ihtiyat;

  /// Fajr and isha substitution when the depression angle is not reached but
  /// a real night still exists.
  @ffi.UnsignedInt()
  external int high_lat_methodAsInt;

  HighLatMethod get high_lat_method =>
      HighLatMethod.fromValue(high_lat_methodAsInt);

  /// Reference latitude used when there is no sunset or sunrise at all, which
  /// is the case inside the polar circle. Every rule above is measured in
  /// units of the night, so without a reference there is nothing to measure
  /// and the affected times are NaN. Set to 0 when the authority publishes no
  /// rule for this case, which is most of them.
  ///
  /// A caller who needs a time anyway can copy the table entry and set this
  /// themselves. That is a deliberate escape hatch: the library will not put
  /// a ruling in an authority's mouth, but it will not stand between a user
  /// and a prayer time either. The choice is then the caller's, and it is
  /// recorded in their code rather than misattributed to the authority.
  ///
  /// MethodParams mine = *method_params_get(CALC_RUSSIA);
  /// mine.high_lat_method = HIGHLAT_ANGLE_BASED;
  /// mine.high_lat_ref = 45.0;
  ///
  /// At Murmansk, 68.97 N, that takes 2025 from 102 days with a non-finite
  /// prescribed time to none. tests/test_prayertimes.c pins both numbers.
  @ffi.Double()
  external double high_lat_ref;
}

/// The five prescribed prayer times, each as decimal hours in local time,
/// so 17.75 means 17:45.
///
/// Sunrise and dhuha were removed in v0.2.0. Sunrise is not a prayer, it
/// is the end of the fajr window, and dhuha is a voluntary prayer carried
/// only by Indonesian timetables. Both are still computed internally,
/// because maghrib is sunset and every high-latitude substitution measures
/// the night between sunset and sunrise, but neither is part of the
/// contract.
///
/// A field is normally in [0, 24), but it is not guaranteed to be, and callers
/// that do anything other than print it must handle two cases.
///
/// Non-finite. Above roughly 66 degrees the Sun can fail to reach the altitude
/// an event is defined by, and the field is then NaN. Test with isfinite()
/// before use. This depends on the method: those carrying a high_lat_ref,
/// currently MWL and Moonsighting, resolve every field at every latitude,
/// and the other 20 do not.
///
/// Outside [0, 24). The high-latitude fallback for fajr and isha can return a
/// value below 0 or at or above 24, meaning the event falls on the previous or
/// the next calendar day. This happens on 107 days a year at Reykjavik and 23
/// at Anchorage under MWL, neither of which produces a NaN, so the two cases
/// are independent.
///
/// The double is the only thing that carries the day offset. Reducing a field
/// into [0, 24) before building a date or a timestamp therefore moves the event
/// silently onto the wrong day. Keep the whole value. format_time_hm() and
/// format_time_hms() handle both cases, but a clock string cannot express a
/// date, so they do not preserve the offset either.
///
/// Whether this struct should carry the offset explicitly is open, see issue
/// #56. Until it is settled the raw value is the contract, and
/// tests/test_prayertimes.c pins it.
final class PrayerTimes extends ffi.Struct {
  @ffi.Double()
  external double fajr;

  @ffi.Double()
  external double dhuhr;

  @ffi.Double()
  external double asr;

  @ffi.Double()
  external double maghrib;

  @ffi.Double()
  external double isha;
}

const double M_PI = 3.141592653589793;

const double DEG_TO_RAD = 0.017453292519943295;

const double RAD_TO_DEG = 57.29577951308232;

const double JULIAN_EPOCH = 2451545.0;

const double SUN_MEAN_ANOMALY_OFFSET = 357.529;

const double SUN_MEAN_ANOMALY_RATE = 0.98560028;

const double SUN_MEAN_LONGITUDE_OFFSET = 280.459;

const double SUN_MEAN_LONGITUDE_RATE = 0.98564736;

const double SUN_ECCENTRICITY_AMPLITUDE1 = 1.915;

const double SUN_ECCENTRICITY_AMPLITUDE2 = 0.02;

const double OBLIQUITY_COEFF = 23.439;

const double OBLIQUITY_RATE = 3.6e-7;

const double REFRACTION_CORRECTION = 0.833;
