// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset(
  'package:libmuslim_dart/libmuslim_dart_bindings_generated.dart',
)
library;

import 'dart:ffi' as ffi;

/// Format a decimal-hours time (e.g. 5.5) into "HH:MM" in outBuffer.
/// Minutes are rounded up (Kemenag convention).
@ffi.Native<ffi.Void Function(ffi.Double, ffi.Pointer<ffi.Char>, ffi.Size)>()
external void format_time_hm(
  double timeHours,
  ffi.Pointer<ffi.Char> outBuffer,
  int bufSize,
);

/// Format a decimal-hours time (e.g. 5.5) into "HH:MM:SS" in outBuffer.
/// Seconds are rounded to nearest; use format_time_hm for the Kemenag
/// round-up-to-the-minute convention.
@ffi.Native<ffi.Void Function(ffi.Double, ffi.Pointer<ffi.Char>, ffi.Size)>()
external void format_time_hms(
  double timeHours,
  ffi.Pointer<ffi.Char> outBuffer,
  int bufSize,
);

/// Look up the parameter set for a calculation method.
/// Returns: pointer to a static MethodParams, or NULL if method is out of range.
@ffi.Native<ffi.Pointer<MethodParams> Function(ffi.UnsignedInt)>(
  symbol: 'method_params_get',
)
external ffi.Pointer<MethodParams> _method_params_get(int method);

ffi.Pointer<MethodParams> method_params_get(CalcMethod method) =>
    _method_params_get(method.value);

/// Map a method key string (e.g. "kemenag") to its CalcMethod.
/// Returns: the matching method, or CALC_CUSTOM if name is NULL or unknown.
@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<ffi.Char>)>(
  symbol: 'method_from_string',
)
external int _method_from_string(ffi.Pointer<ffi.Char> name);

CalcMethod method_from_string(ffi.Pointer<ffi.Char> name) =>
    CalcMethod.fromValue(_method_from_string(name));

/// Map a CalcMethod back to its key string (e.g. "kemenag").
/// Returns: the key, or "custom" if the method has no key.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.UnsignedInt)>(
  symbol: 'method_to_string',
)
external ffi.Pointer<ffi.Char> _method_to_string(int method);

ffi.Pointer<ffi.Char> method_to_string(CalcMethod method) =>
    _method_to_string(method.value);

/// Compute all prayer times for a date and location using the given method.
/// Returns times as decimal hours in local time; high-latitude fallbacks apply.
@ffi.Native<
  PrayerTimes Function(
    ffi.Int,
    ffi.Int,
    ffi.Int,
    ffi.Double,
    ffi.Double,
    ffi.Double,
    ffi.Pointer<MethodParams>,
  )
>()
external PrayerTimes calculate_prayer_times(
  int year,
  int month,
  int day,
  double latitude,
  double longitude,
  double timezone,
  ffi.Pointer<MethodParams> params,
);

/// ── Calculation-method catalogue ──────────────────────────────────────
enum CalcMethod {
  CALC_MWL(0),
  CALC_MAKKAH(1),
  CALC_ISNA(2),
  CALC_EGYPT(3),
  CALC_KARACHI(4),
  CALC_TURKEY(5),
  CALC_SINGAPORE(6),
  CALC_JAKIM(7),
  CALC_KEMENAG(8),
  CALC_FRANCE(9),
  CALC_RUSSIA(10),
  CALC_DUBAI(11),
  CALC_QATAR(12),
  CALC_KUWAIT(13),
  CALC_JORDAN(14),
  CALC_GULF(15),
  CALC_TUNISIA(16),
  CALC_ALGERIA(17),
  CALC_MOROCCO(18),
  CALC_PORTUGAL(19),
  CALC_MOONSIGHTING(20),
  CALC_CUSTOM(21),
  CALC_COUNT(22);

  final int value;
  const CalcMethod(this.value);

  static CalcMethod fromValue(int value) => switch (value) {
    0 => CALC_MWL,
    1 => CALC_MAKKAH,
    2 => CALC_ISNA,
    3 => CALC_EGYPT,
    4 => CALC_KARACHI,
    5 => CALC_TURKEY,
    6 => CALC_SINGAPORE,
    7 => CALC_JAKIM,
    8 => CALC_KEMENAG,
    9 => CALC_FRANCE,
    10 => CALC_RUSSIA,
    11 => CALC_DUBAI,
    12 => CALC_QATAR,
    13 => CALC_KUWAIT,
    14 => CALC_JORDAN,
    15 => CALC_GULF,
    16 => CALC_TUNISIA,
    17 => CALC_ALGERIA,
    18 => CALC_MOROCCO,
    19 => CALC_PORTUGAL,
    20 => CALC_MOONSIGHTING,
    21 => CALC_CUSTOM,
    22 => CALC_COUNT,
    _ => throw ArgumentError('Unknown value for CalcMethod: $value'),
  };
}

enum AsrSchool {
  ASR_STANDARD(1),
  ASR_HANAFI(2);

  final int value;
  const AsrSchool(this.value);

  static AsrSchool fromValue(int value) => switch (value) {
    1 => ASR_STANDARD,
    2 => ASR_HANAFI,
    _ => throw ArgumentError('Unknown value for AsrSchool: $value'),
  };
}

enum HighLatMethod {
  HIGHLAT_NONE(0),
  HIGHLAT_MIDDLE_OF_NIGHT(1),
  HIGHLAT_ONE_SEVENTH(2),
  HIGHLAT_ANGLE_BASED(3);

  final int value;
  const HighLatMethod(this.value);

  static HighLatMethod fromValue(int value) => switch (value) {
    0 => HIGHLAT_NONE,
    1 => HIGHLAT_MIDDLE_OF_NIGHT,
    2 => HIGHLAT_ONE_SEVENTH,
    3 => HIGHLAT_ANGLE_BASED,
    _ => throw ArgumentError('Unknown value for HighLatMethod: $value'),
  };
}

enum MidnightMode {
  MIDNIGHT_STANDARD(0);

  final int value;
  const MidnightMode(this.value);

  static MidnightMode fromValue(int value) => switch (value) {
    0 => MIDNIGHT_STANDARD,
    _ => throw ArgumentError('Unknown value for MidnightMode: $value'),
  };
}

final class MethodParams extends ffi.Struct {
  external ffi.Pointer<ffi.Char> name;

  @ffi.Double()
  external double fajr_angle;

  /// 0 when isha uses interval instead
  @ffi.Double()
  external double isha_angle;

  /// minutes after maghrib (0 = use angle)
  @ffi.Int()
  external int isha_interval;

  /// minutes after sunset (0 = at sunset)
  @ffi.Int()
  external int maghrib_interval;

  /// shadow factor: 1 = standard, 2 = Hanafi
  @ffi.Int()
  external int asr_shadow;

  @ffi.UnsignedInt()
  external int midnight_modeAsInt;

  MidnightMode get midnight_mode => MidnightMode.fromValue(midnight_modeAsInt);

  /// precautionary minutes added to each time
  @ffi.Int()
  external int ihtiyat;
}

final class PrayerTimes extends ffi.Struct {
  @ffi.Double()
  external double fajr;

  @ffi.Double()
  external double sunrise;

  /// Dhuha prayer time (Kemenag: ~28-30 min after sunrise)
  @ffi.Double()
  external double dhuha;

  @ffi.Double()
  external double dhuhr;

  @ffi.Double()
  external double asr;

  @ffi.Double()
  external double maghrib;

  @ffi.Double()
  external double isha;
}

const double M_PI = 3.141592653589793;

const double DEG_TO_RAD = 0.017453292519943295;

const double RAD_TO_DEG = 57.29577951308232;

const double JULIAN_EPOCH = 2451545.0;

const double SUN_MEAN_ANOMALY_OFFSET = 357.529;

const double SUN_MEAN_ANOMALY_RATE = 0.98560028;

const double SUN_MEAN_LONGITUDE_OFFSET = 280.459;

const double SUN_MEAN_LONGITUDE_RATE = 0.98564736;

const double SUN_ECCENTRICITY_AMPLITUDE1 = 1.915;

const double SUN_ECCENTRICITY_AMPLITUDE2 = 0.02;

const double OBLIQUITY_COEFF = 23.439;

const double OBLIQUITY_RATE = 3.6e-7;

const double REFRACTION_CORRECTION = 0.833;

const double DHUHA_ALTITUDE = 4.3;
